#Calificacion MIA 2022

#CREACION DE DISCOS

mkdisk -size=75 -unit=M -path=/tmp/d1.dk               #disco con primer ajuste
mkdisk -unit=K -path=/tmp/d2.dk -fit=BF -size=10240      #tamaño de 10mb
mkdisk -size=101 -path=/tmp/d3.dk -f=WF             #error parametro incorrecto debe ser fit
mkdisk -size=101 -path=/tmp/d3.dk -fit=WF             #debe crear disco en MB
mkdisk -size=1 -path="/tmp/eliminar 1.dk"
mkdisk -size=1 -path="/tmp/eliminar 2.dk"
